spring:
  application:
    name: cookie-provider

server:
  port: 8081

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl.defaultZone: http://localhost:8761/eureka
